apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysb-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysb
  template:
    metadata:
      labels:
        app: mysb
    spec:
      containers:
      - name: mysb-pod
        image: 180.150.207.73:5000/mysb:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysb
spec:
  type: NodePort
  selector:
    app: mysb
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31500