name: CICD test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build, tag, and push image to my private repository
      id: build-image
      run:
        docker build -t 180.150.207.73:5000/myapp:1.0 .
        docker push 180.150.207.73:5000/myapp:1.0