name: Update Deployment Image Tag

on:
  push:
    branches:
      - master

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read deployment.yml
        id: read-yaml
        run: |
          echo "::set-output name=content::$(cat deploy/deployment.yml)"

      - name: Update Image Tag
        id: update-image
        run: |
          echo "${{ steps.read-yaml.outputs.content }}" | sed 's|image: 180.150.207.73:5000/myapp1:{{VERSION}}|image: 180.150.207.73:5000/myapp1:${{ github.run_number }}|' > deploy/deployment.yml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "mastgm0817"
          git config --global user.email "mastgm0817@gmail.com"
          git add deploy/deployment.yml
          git commit -m "Update image tag in deployment.yml"
          git push
